---
title: "Publications & Press"
---

```{css, echo = FALSE}
/* d-article ol {
  display: block;
  margin-bottom: 0em;
} */

d-article p {
  display: block;
  list-style-type: decimal;
  margin-bottom: 0em;
}  

.button1 {
  background-color: #F2E8CF;
  border: none;
  color: #353839; 
  padding: 2px 2px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
  font-family: "Titillium Web", sans-serif;
  font-size: 14px;
  margin: 4px 2px;
  border-radius: 6px;
  cursor: pointer;
  transition-duration: 0.4s;
}

.button1:hover {
  background-color: #73A8A3; /* Green */
  color: #F2E8CF;
}

```

# All
- For all publications in reverse chronological order [click here](publications_all.html), including related summaries, commentaries, press releases, and code.

# Select

```{r child = "./pubs/2024_hat_he_first_wholedrccea.Rmd"}
```
```{r child = "./pubs/2023_rsv_epi_first_burdensplines.Rmd"}
```
```{r child = "./pubs/2021_hat_he_first_framework.Rmd"}
```
```{r child = "./pubs/2019_typhoid_he_middle_globalcea.Rmd"}
```
```{r child = "./pubs/2017_typhoid_meta_first_burden.Rmd"}
```

<!-- # Subsets -->
<!-- Do this with buttons? -->
<!-- ## By disease area -->
<!-- - For typhoid publications, [click here](publications_typhoid.html).   -->
<!-- - For human African trypanosomiasis (HAT) publications, [click here](publications_hat.html).   -->
<!-- - For RSV publications, [click here](publications_rsv.html).   -->
<!-- - For Covid-19 publications, [click here](publications_covid.html).   -->
<!-- - For publications on other diseases, [click here](publications_otherdis.html).   -->

<!-- ## By methodological approach -->
<!-- Some publications span more than one  -->
<!-- - For transmission modeling publications, [click here](publications_transmission.html).  -->
<!-- - For burden modeling publications, [click here](publications_burden.html).   -->
<!-- - For other epidemiology publications (regression-based modeling), [click here](publications_otherepi.html).   -->
<!-- - For health economic publications, [click here](publications_healthecon.html).   -->
<!-- - For meta-regression and meta-analysis publications, [click here](publications_meta.html).   -->
<!-- - For other publications, [click here](publications_othermethods.html).   -->

<!-- ## By authorship -->
<!-- - For first-author publications, [click here](publications_first.html).   -->
<!-- - For senior-author publications, [click here](publications_senior.html).   -->
<!-- - For other publications, [click here](publications_senior.html).   -->

<!-- **Any other press or reports?** -->
